import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import prettier from "eslint-config-prettier";
import tseslint from "typescript-eslint";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/coverage/**",
      "packages/db/generated/**",
      // Generated by Next on every build. Not ours to lint or fix.
      "**/next-env.d.ts",
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  // Next.js rules apply to the web app only. `rootDir` stops the plugin looking for a
  // pages/ directory at the monorepo root and warning that it cannot find one.
  ...compat.extends("next/core-web-vitals").map((config) => ({
    ...config,
    files: ["apps/web/**/*.{ts,tsx}"],
    settings: { ...config.settings, next: { rootDir: "apps/web" } },
  })),

  {
    rules: {
      // docs/CLAUDE.md: no console.log left in a finished ticket. warn/error stay —
      // they are how we surface problems that Sentry should see.
      "no-console": ["error", { allow: ["warn", "error"] }],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  // Must stay last: turns off everything that fights Prettier.
  prettier
);
